# -*- coding: utf-8 -*-
"""Projeto_Trader_Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uCBNV1TvB287HBjhQpmJbb9vCm9WhHFO
"""

''' projeto do grupo MErcado Financeiro no Streamlit'''

import pandas as pd
import yfinance as yf
import streamlit as st
import datetime as dt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# indicadores traders
import talib
from talib import RSI, BBANDS

symbols = ['AAPL', 'AMZN']

ticker = st.sidebar.selectbox(
    'Escolha uma ação',
     symbols)

stock = yf.Ticker(ticker)

df = yf.download(tickers = ticker,
                 start = '2021-01-01',
                 end = '2022-04-19',
                 interval = '1h',
                 ajusted = True)

def criar_rsi(df):
  RSI_PERIOD = 20 # definindo o período considerado para cálculo de RSI
  df['rsi'] = talib.RSI(df['Adj Close'], RSI_PERIOD)  # criando a feature RSI
  return df

df = criar_rsi(df)

st.dataframe(df)
